set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(LLVM_MINGW_ROOT "/home/trevor/.local/toolchains/llvm-mingw-20260421-ucrt-ubuntu-22.04-x86_64" CACHE PATH "llvm-mingw root")
set(LLVM_MINGW_TARGET x86_64-w64-mingw32)

set(CMAKE_C_COMPILER "${LLVM_MINGW_ROOT}/bin/${LLVM_MINGW_TARGET}-clang" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_ROOT}/bin/${LLVM_MINGW_TARGET}-clang++" CACHE FILEPATH "")
set(CMAKE_RC_COMPILER "${LLVM_MINGW_ROOT}/bin/${LLVM_MINGW_TARGET}-windres" CACHE FILEPATH "")
set(CMAKE_AR "${LLVM_MINGW_ROOT}/bin/${LLVM_MINGW_TARGET}-ar" CACHE FILEPATH "")
set(CMAKE_RANLIB "${LLVM_MINGW_ROOT}/bin/llvm-ranlib" CACHE FILEPATH "")
set(CMAKE_STRIP "${LLVM_MINGW_ROOT}/bin/${LLVM_MINGW_TARGET}-strip" CACHE FILEPATH "")

set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW_ROOT}/${LLVM_MINGW_TARGET}" "${LLVM_MINGW_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
